name: CI Workflow

on: [push, pull_request]

jobs:
  go_test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Go Get
        run: go get -v ./...
        env:
          GO111MODULES: on

      - name: Go Build
        run: go build -v ./...
        env:
          GO111MODULES: on

      - name: Go Test
        run: go test -v ./...
        env:
          GO111MODULES: on

  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: go_test
    steps:
      - uses: actions/checkout@master

      - name: Build Docker Image (Push)
        uses: roleypoly/actions-buildkit@master
        if: github.event_name == 'push'
        with:
          tag: ${{ github.repository }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Retag Image
        if: github.event_name == 'push'
        run: |
          retag() {
            curl -sSL https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64 > $HOME/buildx &&\
            chmod a+x $HOME/buildx &&\
            $HOME/buildx imagetools create --tag "${{ github.repository }}:$1" "${{ github.repository }}:${{ github.sha }}"
          }
          test ${{ github.ref }} = "refs/heads/master" && retag latest || \
          test ${{ github.ref }} = "refs/heads/develop" && retag next || \
          test ${{ github.ref }} = "refs/heads/ci-testing" && retag scratch || \
          echo "not a well-known branch, not retagging"
