name: CI Workflow

on: [push, pull_request]

jobs:
  go_test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Go Get
        run: go get -v ./...
        env:
          GO111MODULES: on

      - name: Go Build
        run: go build -v ./...
        env:
          GO111MODULES: on

      - name: Go Test
        run: go test -v ./...
        env:
          GO111MODULES: on

  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: go_test
    steps:
      - uses: actions/checkout@master

      - name: Buildkit master to :latest
        uses: roleypoly/actions-buildkit@master
        if: github.ref == 'refs/heads/master'
        with:
          tag: roleypoly/discord:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v6
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Buildkit develop to :next
        uses: roleypoly/actions-buildkit@master
        if: github.ref == 'refs/heads/develop'
        with:
          tag: roleypoly/discord:next
          platforms: linux/amd64,linux/arm64,linux/arm/v6
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
