name: CI Workflow

on: [push, pull_request]

jobs:
  go_test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Go Get
        run: go get -v ./...
        env:
          GO111MODULES: on

      - name: Go Build
        run: go build -v ./...
        env:
          GO111MODULES: on

      - name: Go Test
        run: go test -v ./...
        env:
          GO111MODULES: on

  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: go_test
    steps:
      - uses: actions/checkout@master

      - name: Build & Tag
        uses: actions/docker/cli@master
        with:
          args: build . -t roleypoly/discord:${{ github.sha }} --build-arg GO_VERSION=1.13

      - name: Login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Tag & Push master to :latest
        uses: actions/docker/cli-multi@master
        if: github.ref == 'refs/heads/master'
        with:
          args: '"tag roleypoly/discord:${{ github.sha }} roleypoly/discord:latest" "push roleypoly/discord:latest"'

      - name: Tag & Push develop to :next
        uses: actions/docker/cli-multi@master
        if: github.ref == 'refs/heads/develop'
        with:
          args: '"tag roleypoly/discord:${{ github.sha }} roleypoly/discord:next" "push roleypoly/discord:next"'
