name: CI Workflow

on: [push, pull_request]

jobs:
  go_test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.x

      - name: Go Get
        run: go get -v ./...
        env:
          GO111MODULES: on

      - name: Go Build
        run: go build -v ./...
        env:
          GO111MODULES: on

      - name: Go Test
        run: go test -v ./...
        env:
          GO111MODULES: on

  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        uses: actions/docker/cli@master
        with:
          args: build -t roleypoly/discord:${{ github.sha }}

      - name: Login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Re-tag master
        uses: actions/docker/tag@master
        if: github.ref == 'refs/head/master'
        with:
          args: roleypoly/discord:${{ github.sha }} roleypoly/discord:latest

      - name: Re-tag develop
        uses: actions/docker/tag@master
        if: github.ref == 'refs/head/develop'
        with:
          args: roleypoly/discord:${{ github.sha }} roleypoly/discord:next

      - name: Push
        uses: actions/docker/cli@master
        with:
          args: push roleypoly/discord:latest roleypoly/discord:next
